apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        # image: nginx:1.14.2
        # ports:
        # - containerPort: 80
        build:
          context: ./
          dockerfile: ./Dockerfile
