version: '3'
services:
  nacos:
    image: nacos/nacos-server:2.0.1
    ports:
      - '8848:8848'
    environment:
      - 'MODE=standalone'
      - 'SPRING_DATASOURCE_PLATFORM=mysql'
      - 'MYSQL_SERVICE_HOST=49.233.10.187'
      - 'MYSQL_SERVICE_DB_NAME=nacos_config'
      - 'MYSQL_SERVICE_USER=root'
      - 'MYSQL_SERVICE_PASSWORD=lidaning'
    restart: unless-stopped
  checkin:
#    image: 'lidaning/checkin:1.0'
    build:
      context: ./
      dockerfile: ./checkin/Dockerfile
    ports:
      - '5020:5020'
    environment:
      - 'TZ=Asia/Shanghai'
#    networks:
#      default:
#        ipv4_address: 192.168.1.7
    restart: unless-stopped
    depends_on:
      - nacos
  todos:
#    image: 'lidaning/todos:1.0'
    build:
      context: ./
      dockerfile: ./todos/Dockerfile
    ports:
      - '5070:5070'
    environment:
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
    depends_on:
      - nacos
#  countcrying:
#    image: 'lidaning/countcrying:1.0'
#    build:
#      context: ./
#      dockerfile: ./countcrying/Dockerfile
#    ports:
#      - '5000:5000'
#    environment:
#      - 'TZ=Asia/Shanghai'
  studyplan:
#    image: 'lidaning/studyplan:1.0'
    build:
      context: ./
      dockerfile: ./studyplan/Dockerfile
    ports:
      - '5030:5030'
    environment:
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
    depends_on:
      - nacos
  encourager:
#    image: 'lidaning/encourager:1.0'
    build:
      context: ./
      dockerfile: ./encourager/Dockerfile
    ports:
      - '5050:5050'
    environment:
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
    depends_on:
      - nacos
  review:
    build:
      context: ./
      dockerfile: ./review/Dockerfile
    ports:
      - '5080:5080'
    environment:
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
    depends_on:
      - nacos
#  grocery:
#    build:
#      context: ./
#      dockerfile: ./grocery/Dockerfile
#    ports:
#      - '5100:5100'
#    environment:
#      - 'TZ=Asia/Shanghai'
#    volumes:
#    - "/apps/resource:/apps/resource"
  auth:
    build:
      context: ./
      dockerfile: ./auth/manifest/Dockerfile
    ports:
      - '4090:4090'
    environment:
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
    # depends_on:
    #   - nacos

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.1.0/24
#          gateway: 192.168.1.1