version: '3'
services:
  checkin:
#    image: 'lidaning/checkin:1.0'
    build:
      context: ./
      dockerfile: ./checkin/Dockerfile
    ports:
      - '5020:5020'
    environment:
      - 'TZ=Asia/Shanghai'
#    networks:
#      default:
#        ipv4_address: 192.168.1.7
  todos:
#    image: 'lidaning/todos:1.0'
    build:
      context: ./
      dockerfile: ./todos/Dockerfile
    ports:
      - '5070:5070'
    environment:
      - 'TZ=Asia/Shanghai'
  countcrying:
#    image: 'lidaning/countcrying:1.0'
    build:
      context: ./
      dockerfile: ./countcrying/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - 'TZ=Asia/Shanghai'
  studyplan:
#    image: 'lidaning/studyplan:1.0'
    build:
      context: ./
      dockerfile: ./studyplan/Dockerfile
    ports:
      - '5030:5030'
    environment:
      - 'TZ=Asia/Shanghai'
  encourager:
#    image: 'lidaning/encourager:1.0'
    build:
      context: ./
      dockerfile: ./encourager/Dockerfile
    ports:
      - '5050:5050'
    environment:
      - 'TZ=Asia/Shanghai'
  review:
    build:
      context: ./
      dockerfile: ./review/Dockerfile
    ports:
      - '5080:5080'
    environment:
      - 'TZ=Asia/Shanghai'
  grocery:
    build:
      context: ./
      dockerfile: ./grocery/Dockerfile
    ports:
      - '5100:5100'
    environment:
      - 'TZ=Asia/Shanghai'
#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.1.0/24
#          gateway: 192.168.1.1