apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
  labels:
    app: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: lidaning/todos
        imagePullPolicy: Always
        ports:
        - containerPort: 5070
